plugins {
    id 'com.android.application'
}

android {
    namespace 'br.com.thiaguinhosolucoes.thamismibro'
    compileSdk 35

    defaultConfig {
        applicationId "br.com.thiaguinhosolucoes.thamismibro"
        minSdk 26
        targetSdk 35
        versionCode 101
        versionName "1.0.1"
    }

    sourceSets {
        main {
            assets.srcDirs = ['../../web']
        }
    }

    buildTypes {
        debug { debuggable true }
        release { minifyEnabled false }
    }
}

dependencies { }
